### ISSUE TITLE
TimelineSignal works only once

### ISSUE THREAD

**Issue by milkcocoa** [monry/EventConnector#93]
I use `TimelineSignal` with a toggle button (like showing / hiding something).

This toggle feature is performed with timelines, so I need to play them multiple times. `TimelineSignal`, however, passes the event only once, since it has `Take(1)`.

So, I'd like to omit this `Take(1)` from `TimelineSignal`. What do you think of it?

**Comment by monry** [comment]
I think there is no problem.
I don't remember why I added `Take (1)`, but I don't think it is necessary.

**Comment by milkcocoa** [comment]
Thank you,  I'll create a PR!

**Comment by milkcocoa** [comment]
#125 has been merged! Thanks.
